# Generated by Django 4.1.4 on 2023-03-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customer_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model_name',
            field=models.CharField(choices=[('modelA', 'modelA'), ('modelB', 'modelB')], max_length=100),
        ),
    ]
